backend:
  name: git-gateway
  branch: main

media_folder: /src/images/uploads

collections:
  - name: "Favorites"
    label: 'Favorites'
    folder: '/src/images/uploads/'
    create: true
    media_folder: 'favorites'
    fields:
      - label: "Manage Images"
        name: "image"
        widget: "image"
        media_folder: '/src/images/uploads/favorites'
  - name: "Illustrations"
    label: 'Illustrations'
    folder: '/src/images/uploads/'
    create: true
    media_folder: 'illustrations'
    fields:
      - label: "Add Image(s)"
        name: "image"
        widget: "image"
        media_folder: '/src/images/uploads/illustrations'
  - name: "Animations"
    label: 'Animations'
    folder: '/src/images/uploads/'
    create: true
    media_folder: 'animations'
    fields:
      - label: "Add Video(s)"
        name: "video"
        widget: "file"
        media_folder: '/src/images/uploads/animations'
  - name: "CharacterDesigns"
    label: 'Character Designs'
    folder: '/src/images/uploads/'
    create: true
    media_folder: 'characterDesigns'
    fields:
      - label: "Add Image(s)"
        name: "image"
        widget: "file"
  - name: "StoryBoards"
    label: 'Story Boards'
    folder: '/src/images/uploads/'
    create: true
    media_folder: 'storyBoards'
    fields:
      - label: "Add Image(s)"
        name: "image"
        widget: "file"
